name: pipeline

on: [push]

permissions:
  contents: write

jobs:
  go:
    uses: pete911/github-actions/.github/workflows/go.yml@main
  go-release:
    needs:
      - go
    uses: pete911/github-actions/.github/workflows/go-releaser.yml@main
    secrets:
      PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
